[package]
name = "amberwindow"
version = "0.1.2"
edition = "2021"
description = "An easy to use ImmediateMode gui library for Rust."
license = "MIT" 

[dependencies]
macroquad = "0.4.8"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3